[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

[libraries]
paper = "com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT"
spigot = "org.spigotmc:spigot-api:1.12.2-R0.1-SNAPSHOT"
configurate = "org.spongepowered:configurate-hocon:4.1.2"
minimessage = "net.kyori:adventure-text-minimessage:4.14.0"